name = "lorealchatbot"
main = "worker.js"
compatibility_date = "2024-01-01"

# Environment variables
[vars]
OPENAI_API_URL = "https://api.openai.com/v1/chat/completions"
OPENAI_MODEL = "gpt-4o"

# CORS configuration
[env.production]
routes = [
  "your-domain.com/api/*"
]

[env.development]
# Local development settings
# Local development settings
